"""Restore proactive messaging tables

Revision ID: 45b76fed7e0f
Revises: d47a7577fc4b
Create Date: 2025-08-13 15:57:54.170021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b76fed7e0f'
down_revision: Union[str, None] = 'd47a7577fc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.create_index('idx_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_goal_order', 'tasks', ['goal_id', 'order_index'], unique=False)
    op.create_index('idx_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.drop_column('tasks', 'estimated_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_time', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('idx_user_status', table_name='tasks')
    op.drop_index('idx_goal_order', table_name='tasks')
    op.drop_index('idx_due_date', table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
