"""Add proactive messaging fields to chat

Revision ID: e695c9689326
Revises: 5b9a27b55b88
Create Date: 2025-08-12 23:56:23.492275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e695c9689326'
down_revision: Union[str, None] = '5b9a27b55b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_proactive', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('trigger_type', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('trigger_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'trigger_context')
    op.drop_column('chat_messages', 'trigger_type')
    op.drop_column('chat_messages', 'is_proactive')
    # ### end Alembic commands ###
